### PR TITLE
Fix: #2239 merge types on runtime merge

### LINKED ISSUE #2239: Merge type inference
**Describe the bug**

Type checking for `define-data-var` fails for some merged records.   

**Steps To Reproduce**

Evaluate in the [Clarity REPL](https://lgalabru.github.io/clarity-repl/)

```lisp
(define-data-var a {p: uint} (merge {p: 2} {p: u2}))
=> Runtime Error: Unchecked(TypeValueError(TupleType(TupleTypeSignature { type_map: {ClarityName("p"): UIntType} }), Tuple(TupleData { type_signature: TupleTypeSignature { type_map: {ClarityName("p"): IntType} }, data_map: {ClarityName("p"): UInt(2)} })))
```
Another unexpected result:

```lisp
(define-data-var b {p: int, q: int} (merge {p: 2} {q: 3}))
=> Runtime Error: Unchecked(TypeValueError(TupleType(TupleTypeSignature { type_map: {ClarityName("p"): IntType, ClarityName("q"): IntType} }), Tuple(TupleData { type_signature: TupleTypeSignature { type_map: {ClarityName("q"): IntType} }, data_map: {ClarityName("p"): Int(3), ClarityName("q"): Int(2)} })))
```

In contrast, these evaluate without fail:
```lisp
(merge {p: 2} {p: u2})
(merge {p: 2} {q: 3})
(define-data-var c {p: uint} {p: u2})
(define-data-var d {p: uint} (merge {p: u2} {p: u2}))
(define-data-var e {p: int, q: int} {p: 2, q: 3})
(define-data-var f {p: int, q: int} (merge {q: 2, p: 3} {p: 4}))
```

**Expected behavior**

The records are merged without fail to the expected initial value for the defined var.

### PR DESCRIPTION
**Pull request by kantai**
This fixes #2239, and provides a witnessing test.

### CODE REVIEW

File: src/vm/tests/simple_apply_eval.rs [hunk 1]
```diff
@@ -929,6 +929,36 @@ fn test_lets() {
         .for_each(|(program, expectation)| assert_eq!(expectation.clone(), execute(program)));
 }
 
+#[test]
+fn test_2239_merge() {
```
Comment (jcnelson) [inline src/vm/tests/simple_apply_eval.rs:933]: Can we have a more descriptive test name?  Naming code after GH issues is a pet peeve of mine, because unless you're willing to trawl through the GH issue list, you won't know what the context for the test is.

File: src/vm/tests/simple_apply_eval.rs [hunk 2]
```diff
@@ -929,6 +929,36 @@ fn test_lets() {
...
+    let tests = [
+        "(define-data-var a {p: uint} (merge {p: 2} {p: u2})) (var-get a)",
+        "(merge {p: 2} {p: u2})",
+        "(merge {p: 2} {q: 3})",
+        "(define-data-var c {p: uint} {p: u2}) (var-get c)",
+        "(define-data-var d {p: uint} (merge {p: u2} {p: u2})) (var-get d)",
+        "(define-data-var e {p: int, q: int} {p: 2, q: 3}) (var-get e)",
+        "(define-data-var f {p: int, q: int} (merge {q: 2, p: 3} {p: 4})) (var-get f)",
```
Comment (jcnelson) [inline src/vm/tests/simple_apply_eval.rs:941]: Do you maybe want to add the specific test that triggered this problem?

**Review by jcnelson — APPROVED** [review]
LGTM!

File: src/vm/tests/simple_apply_eval.rs (hunk 2 above)
Comment (kantai) [reply src/vm/tests/simple_apply_eval.rs:944]: It's the first test in the list.

File: src/vm/tests/simple_apply_eval.rs (hunk 1 above)
Comment (kantai) [reply src/vm/tests/simple_apply_eval.rs]: Sure, added more description. The advantage of including the issue number in the test name is that it makes running the single test much easier. `cargo test <test-name>` doesn't "regex match", it just does substring matching, so if test names are substrings of one another, it's impossible to just run one test.

**Review by lgalabru — APPROVED** [review]
Looks good to me, thank you @kantai!
