### PR TITLE
Fix/1623

### LINKED ISSUE #1623: Mocknet panicked after submitting a transaction
**Describe the bug**

Mocknet panicked:

```
INFO [1590170230.907] [src/chainstate/stacks/db/transactions.rs:511] Contract-call to ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M.flip-coin.ClarityName("bet") args [UInt(10), Bool(true)] returned Response(ResponseData { committed: true, data: UInt(15) })
INFO [1590170230.907] [src/chainstate/stacks/db/transactions.rs:512] Contract-call to ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M.flip-coin.ClarityName("bet") args [UInt(10), Bool(true)] cost ExecutionCost { write_length: 376, write_count: 7, read_length: 6292, read_count: 14, runtime: 9534 }
thread 'main' panicked at 'Tried to debit 247 from account ST1JDEC841ZDWN9CKXKJMDQGP5TW1AM10B7EV0DV9 (which only has 246)', src/chainstate/stacks/db/accounts.rs:167:17
```

**Steps To Reproduce**
This happened during trying [flip-coin contract](https://github.com/friedger/clarity-smart-contracts/blob/master/contracts/experiments/flip-coin.clar) and after I submitted transaction in https://github.com/friedger/clarity-smart-contracts/blob/master/test/integration/flip-coin2.ts

1. start mocknet with some stx for addresses in keys.json and keys2.json
1. clone repo and run `yarn` in the repo folder
1. deploy contract `yarn mocha test/integration/flip-coin0.ts`
1. call `bet` function: `yarn mocha test/integration/flip-coin1.ts`
1. adjust `betAtHeight` with the result from previous transaction and call `yarn mocha test/integration/flip-coin-x.ts` to check whether user won (should get winner returns some value - type 9)  (if none - type 10 - restart the process).
1. call `bet` to force payout`yarn mocha test/integration/flip-coin2.ts`
1. mocknet panics.

**Expected behavior**
mocknet should not crash

**Environment (please complete the following information):**
stacks-blockstack master commit 57f070775c1a5316e86d72e33e9148dd09e32b1f

starting node with 
```
[[mstx_balance]]
address = "ST1JDEC841ZDWN9CKXKJMDQGP5TW1AM10B7EV0DV9"
amount = 256

[[mstx_balance]]
address = "ST398K1WZTBVY6FE2YEHM6HP20VSNVSSPJTW0D53M"
amount = 67584
```

### PR DESCRIPTION
**Pull request by jcnelson**
This PR fixes #1623.  The problem arises because we need to bill accounts for their transaction fees _after_ we run their payloads, because (eventually) we only want to bill them for the resources they actually used.  If a payload is a `contract-call` that liquidates the account's STX, then the act of paying the transaction fee would cause a runtime panic.  This PR ultimately fixes it by re-loading the payer account after running the transaction payload and using that account's balance to decide if it can pay.

While trying to reproduce the issue, I noticed a small bug in the mempool scanning logic that could cause transactions to get mined out-of-order.  This PR also adjusts the mempool scanning logic to sort all transactions by origin nonce, instead of by fee.  This way, if there are multiple transactions in the mempool from the same origin account, but with different nonces, they'll be mined in the right order in the same block (otherwise, they would have been spaced out across multiple blocks as they became eligible).

### CODE REVIEW

File: src/chainstate/stacks/db/mod.rs [hunk 1]
```diff
@@ -1056,6 +1056,19 @@ pub mod test {
         StacksChainState::open(mainnet, chain_id, &path).unwrap()
     }
 
+    pub fn instantiate_chainstate_with_balances(mainnet: bool, chain_id: u32, test_name: &str, balances: Vec<(StacksAddress, u64)>) -> StacksChainState {
```
Comment (kantai) [inline src/chainstate/stacks/db/mod.rs:1059]: Should this be marked `#[cfg(test)]`?

**Comment by kantai** [comment]
This looks good to me, thanks for the fix @jcnelson!

I think the changes in the miner require an update to some integration tests, though -- for example,

```
tests::integrations::bad_contract_tx_rollback
```

Appears to be failing (that test is in the `stacks-node` project, so it only runs if you run with `cargo test` with `--workspace`) -- it used to be the case that only 3 of the submitted transactions would get include in one block, but now all of them can be included (because of the improved nonce check).

File: src/chainstate/stacks/db/mod.rs (hunk 1 above)
Comment (jcnelson) [reply src/chainstate/stacks/db/mod.rs:1059]: It is -- the module it's declared in is `#[cfg(test)]`.
