### PR TITLE
Fix/neon fixes 20200507

### LINKED ISSUE #1543: Follower panicked at 'attempt to add with overflow'
**Describe the bug**
Follower crashed with following stack trace:

```
thread '<unnamed>' panicked at 'attempt to add with overflow', src/util/db.rs:443:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.r
s:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::panicking::panic
             at src/libcore/panicking.rs:70
  15: blockstack_lib::util::db::tx_busy_handler
             at src/util/db.rs:443
  16: rusqlite::busy::<impl rusqlite::Connection>::busy_handler::busy_handler_callback::{{closure}}
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/busy.rs:52
  17: std::panicking::try::do_call
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:287
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  19: std::panicking::try
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panicking.rs:265
  20: std::panic::catch_unwind
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/panic.rs:396
  21: rusqlite::busy::<impl rusqlite::Connection>::busy_handler::busy_handler_callback
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/busy.rs:52
  22: sqlite3InvokeBusyHandler
             at sqlite3/sqlite3.c:154308
  23: btreeInvokeBusyHandler
             at sqlite3/sqlite3.c:65175
  24: sqlite3BtreeBeginTrans
             at sqlite3/sqlite3.c:66334
  25: sqlite3VdbeExec
             at sqlite3/sqlite3.c:86227
  26: sqlite3Step
             at sqlite3/sqlite3.c:81338
  27: sqlite3_step
             at sqlite3/sqlite3.c:81401
  28: sqlite3_exec
             at sqlite3/sqlite3.c:117981
  29: rusqlite::InnerConnection::execute_batch
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/lib.rs:930
  30: rusqlite::Connection::execute_batch
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/lib.rs:309
  31: rusqlite::transaction::Transaction::new
             at /Users/diwaker/.cargo/registry/src/github.com-1ecc6299db9ec823/rusqlite-0.16.0/src/transaction.rs:101
  32: blockstack_lib::util::db::tx_begin_immediate
             at src/util/db.rs:458
  33: blockstack_lib::chainstate::burn::db::burndb::BurnDB::tx_begin
             at src/chainstate/burn/db/burndb.rs:1172
  34: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block
             at src/burnchains/burnchain.rs:749
  35: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::sync_with_indexer::{{closure}
}
             at src/burnchains/burnchain.rs:902
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
WARN [1588808783.267] [src/burnchains/burnchain.rs:936] Failed to join burnchain download thread: DBError(SqliteError(Sq
liteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))))
ERROR [1588808783.267] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:143] Unable to sync with burnch
ain: Try synchronizing again
```

**Steps To Reproduce**

Using this config (note I'm using the `working_dir`):
```toml
[node]
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
bootstrap_node = "048dd4f26101715853533dee005f0915375854fd5be73405f679c1917a5d4d16aaaf3c4c0d7a9c132a36b8c5fe1287f07dad8c910174d789eb24bdfb5ae26f5f27@neon.blockstack.org:20444"
working_dir = "/Users/diwaker/Desktop/stacks-testnet-neon"

[burnchain]
chain = "bitcoin"
mode = "neon"
peer_host = "neon.blockstack.org"
rpc_port = 18443
peer_port = 18444

#mstx stanzas omitted
```

**Environment (please complete the following information):**
 - OS: OS X
 - git-rev dd6778e4d6c587d90fba9df692bb4a40b0c55ef3

**Additional context**
Also saw a lot of these in the logs:

```
WARN [1588808621.447] [testnet/stacks-node/src/neon_node.rs:239] Relayer buffer is full, dropping NetworkHandle
```

### PR DESCRIPTION
**Pull request by jcnelson**
This PR does the following:

* Fixes #1543 by adding a busy-handler to all SQLite connections that will implement exponential backoff

* Fixes the stacks block header hash cache logic, which previously had been constantly missing hits.  Speed-up on a spinning rust disk is at least 10x.

* Adds relayer back-pressure awareness to the Neon p2p thread.  If the relayer is lagging behind in receiving downloaded blocks, the p2p thread will buffer them up and ask the p2p network to stop asking for them until the relayer's pressure is releaved.  At the same time, the p2p thread will wake up the relayer more frequently if there are pending blocks to process, so idle network activity won't delay block processing.  Also, the p2p thread will wake _itself_ up more frequently if it detects that it's doing its initial block download, so it will more quickly transition to fetching the next batch of blocks (but, it will take the relayer's back-pressure into account when doing so).

* (TODO) speed up querying the scheduled miner payments.  This currently takes 1-2 seconds on my spinning rust disk.  We can and should cache the `MinerPaymentSchedule` instances into the `StacksChainState` for the last `MINER_REWARD_WINDOW` blocks.

### CODE REVIEW

File: testnet/stacks-node/src/neon_node.rs [hunk 1]
```diff
@@ -228,22 +229,73 @@ fn spawn_peer(mut this: PeerNetwork, p2p_sock: &SocketAddr, rpc_sock: &SocketAdd
...
 
+    // buffer up blocks to store without stalling the p2p thread
+    let mut results_with_data = VecDeque::new();
+    let mut wokeup_relayer = false;
+
     let server_thread = thread::spawn(move || {
         loop {
-            let network_result = this.run(&burndb, &mut chainstate, &mut mem_pool, Some(&mut dns_client), poll_timeout)
+            let download_backpressure = results_with_data.len() > 0;
+            let has_attacheable_blocks = StacksChainState::has_attacheable_staging_blocks(&chainstate.blocks_db).expect("BUG: failed to query available staging blocks");
```
Comment (kantai) [inline testnet/stacks-node/src/neon_node.rs:239]: Why does the p2p thread need to poll the Stacks chain state for attachable blocks?

Comment (jcnelson) [reply testnet/stacks-node/src/neon_node.rs:239]: The relayer thread needs to get woken up in order to call `process_blocks()`, which will process up to a given number of attachable blocks.  Right now, the relayer thread is driven entirely by its communication channel from the network thread, so as a short-term hack I made it so the network thread will use the channel to wake up the relayer when there's work for it to do.

I'm not satisfied with this, however.  I'll make it so the relayer thread just does a `try_recv()` to get data, and if there's no new data, it just calls `process_blocks(1)` on receive failure.

Comment (kantai) [reply testnet/stacks-node/src/neon_node.rs:239]: That seems less than ideal as well -- the relayer thread really should only wake when it receives an event on it's channel. Shouldn't this just be an event fired from p2p.run (which is where the blocks are moving to the attachable state, right?)

Comment (jcnelson) [reply testnet/stacks-node/src/neon_node.rs:239]: > Shouldn't this just be an event fired from p2p.run (which is where the blocks are moving to the attachable state, right?)

Actually no.  Blocks are marked as attachable once they're stored to staging, which happens within `process_blocks()`, which is in turn called by the relayer's `process_network_result()` method.  The relayer will always process up to `new_blocks.len() + C` blocks per call to `process_network_result()`, and those blocks will either be marked as orphaned or will be marked as included in the chainstate (either way, they're no longer attachable).

I'd like to keep the p2p thread as responsive as possible to network requests, which is why I thought it would be appropriate to have the relayer deciding when it's okay to process more blocks.

Comment (kantai) [reply testnet/stacks-node/src/neon_node.rs:239]: So, the case this is trying to address is the case where the relayer thread has called `process_blocks`, but that call didn't finish processing all the possible processable blocks, so it needs to call `process_blocks` again?

Comment (jcnelson) [reply testnet/stacks-node/src/neon_node.rs:239]: > So, the case this is trying to address is the case where the relayer thread has called process_blocks, but that call didn't finish processing all the possible processable blocks, so it needs to call process_blocks again?

Yes, but there's more to this that this snippit of code is addressing.  What happens now, without this patch, is the p2p network will download blocks faster than the relayer can process them.  What ultimately happens is the p2p network ends up dropping the downloaded blocks because the channel gets too full of network results (this happens even if we only pass along network results that contain blocks).  This, in turn, causes the p2p network to re-download blocks needlessly, because until the relayer gets around to storing them, the p2p network will believe that it still needs to get them.  Moreover, dropping blocks slows the node's block-processing down, since it won't be able to process any blocks after the dropped ones until the downloader gets around to discovering that the blocks were missing (i.e. the downloader does a best-effort sweep of all winning sortitions, and only comes back to re-trying failed downloads on the next sweep).

At the same time, we can't synchronously send the blocks to the relayer either, since this will just cause the p2p network thread to stall once the channel is full.  But, if we know that the receiver channel is not full (i.e. there's no backpressure), then the p2p network thread should be fetching _new_ blocks as quickly as possible.

What this code is trying to do is making it so the p2p code fetches blocks as quickly as possible while there is no backpressure, but cease fetching blocks once there is backpressure (but continue to process all other network requests).  In addition, if the p2p code receives a block, microblock, or transaction while there is backpressure, or if backpressure arises in the middle of doing so, then this code causes the p2p thread to buffer the results in a `VecDeque` outside the channel and continuously try to forward it to the relayer until the backpressure subsides.  Once backpressure subsides, the p2p thread can resume downloading blocks as quickly as possible.

There's some related code in the downloader that ensures that a block doesn't get re-downloaded more than XXX seconds.  This is in place because even with backpressure control, the p2p network doesn't know if the relayer is sitting on blocks that are yet to be processed.  Depending on your feedback, I could remove this code and simply have the p2p thread keep its own tabs on which blocks are in-flight to the relayer, and have it tell the downloader to not download them again even though they haven't reached the disk yet.

Comment (jcnelson) [reply testnet/stacks-node/src/neon_node.rs:239]: > Depending on your feedback, I could remove this code and simply have the p2p thread keep its own tabs on which blocks are in-flight to the relayer, and have it tell the downloader to not download them again even though they haven't reached the disk yet.

Actually, I think I will just do this now.  My neon follower re-downloads over 1,000 blocks during spin-up, which is not okay.

**Comment by jcnelson** [comment]
Let's move the discussion over to https://github.com/blockstack/stacks-blockchain/pull/1563.  I had to rename this branch so it would run the full CircleCI tests (it modifies the downloader behavior).
