### PR TITLE
Make Neon nodes more resilient 

### LINKED ISSUE #1488: [Follower node crash] Unable to sync burnchain: Invalid argument (os error 22)
**Describe the bug**
Had two separate follower nodes crash at around block 410.

(See full debug log in comment below)
```
stacks-blockchain_1  | INFO [1587722469.382] [/usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/6356b41/src/net/chat.rs:1067] convo:id=114,outbound=true,peer=facade01+80000000://V4(35.245.47.179:20444): failed to recv on P2P conversation: PermanentlyDrained
stacks-blockchain_1  | INFO [1587722469.383] [/usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/6356b41/src/net/p2p.rs:449] No open socket for 114
stacks-blockchain_1  | WARN [1587722491.264] [/usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/6356b41/src/net/p2p.rs:942] Failed to get peer address of TcpStream { addr: V4(172.26.0.3:45240), fd: 38 }: Os { code: 107, kind: NotConnected, message: "Transport endpoint is not connected" }
stacks-blockchain_1  | ERROR [1587722506.856] [/usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/6356b41/src/burnchains/bitcoin/network.rs:237] Failed to connect to peer 35.245.47.179:18444: connection to peer could not be (re-)established
stacks-blockchain_1  | ERROR [1587722523.407] [/usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/6356b41/src/burnchains/bitcoin/network.rs:237] Failed to connect to peer 35.245.47.179:18444: connection to peer could not be (re-)established
stacks-blockchain_1  | WARN [1587722523.407] [/usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/6356b41/src/burnchains/bitcoin/network.rs:248] Connection broken; retrying in 18.362285358864273 sec...
stacks-blockchain_1  | WARN [1587722542.830] [/usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/6356b41/src/burnchains/burnchain.rs:799] Detected burnchain reorg at height 1252 (< 1267). Re-sync'ing...
stacks-blockchain_1  | ERROR [1587722542.831] [/usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/6356b41/testnet/src/burnchains/bitcoin_regtest_controller.rs:138] Unable to sync burnchain: Invalid argument (os error 22)
stacks-blockchain_1  | thread 'main' panicked at 'explicit panic', /usr/local/cargo/git/checkouts/stacks-blockchain-e574f41bf84d9c41/6356b41/testnet/src/burnchains/bitcoin_regtest_controller.rs:139:17
```
**Environment (please complete the following information):**
* Latest core-node master (as of writing this issue) https://github.com/blockstack/stacks-blockchain/commit/6356b41e0e8e7115204cac43450ff56ea3ceec51
* One node running on MacOS, the other running on Ubuntu

### LINKED ISSUE #1500: Burn database must record which Stacks blocks are accepted and orphaned
This is required to determine which Stacks block is the canonical chain tip.  It is precisely the Stacks block that has the highest block height of all Stacks blocks recorded to the canonical burn chain tip.  Right now, we do not enforce the requirement that the Stacks block is on the canonical burn chain tip, which is a bug.  Fixing this is a blocker to fixing #1488.

### PR DESCRIPTION
**Pull request by jcnelson**
This PR makes Neon nodes more resilient than they are today.  It does so in a few ways, based on the early feedback we've gotten since the Neon testnet launch:

* If a Neon master node is rebooted, a Neon follower will automatically track the new Bitcoin chain by treating it as a deep Bitcoin reorg (i.e. back to the genesis block).  The old Bitcoin and Stacks chain state will be preserved; they'll just be rendered as state from non-canonical forks.

* If the shared Bitcoin node is restarted, then Neon miners will automatically begin mining on the new chain instead once the new Bitcoin's chain history overtakes the old one.  This PR fixes #1500 in order to achieve this -- even though the new Stacks chain will be (much) shorter than the old one, it is the canonical chain because it is present on the canonical Bitcoin chain (whereas the old one is not).

* Bitcoin headers are now stored in a Sqlite3 database (#1472) to keep them durable in the face of flaky filesystem implementations (looking at you, Docker on Mac OS).  This should help with #1488. 

* This PR fixes the SPV block work logic so it works on regtest (which has different difficulty parameters).  Neon nodes should no longer reboot at block 2016 -- the end of the first difficult adjustment window.  This should fix #1488 and #1503.

## How it works

The fix for #1500 is not trivial, and warrants further explanation.  The bug this PR fixes is that a node today will determine the canonical Stacks fork as the longest Stacks fork _in existence_, across _all_ burn chain forks.  This is incorrect behavior -- the canonical Stacks fork is the longest Stacks fork _on the canonical burn chain fork_.

How does this PR fix #1500?  It does so by altering the `BurnDB` such that each `BlockSnapshot` contains a pointer to the longest Stacks fork on the burn chain fork it identifies (recall that a `BlockSnaphot` is a burn chain tip).  This pointer is stored in the new `canonical_stacks_tip_height`, `canonical_stacks_tip_hash`, and `canonical_stacks_tip_burn_hash` columns.  To keep this pointer up-to-date, this PR alters `StacksChainState::process_next_staging_block()` to not only mark an anchored Stacks block as accepted in the `staging.db` file, but also to mark the corresponding `BlockSnapshot` that elected it as containing a now-accepted Stacks block.  This information is recorded in the `stacks_block_accepted` and `stacks_block_height` columns.  In summary, each `BlockSnapshot` now contains information as to whether or not the block it elected has been accepted into the chain state, and it contains a pointer to the longest Stacks blockchain fork in all of its ancestor `BlockSnapshots`.

The bulk of the complexity of this PR is in _how_ this pointer is maintained in the face of Stacks blocks being processed.  Stacks blocks are downloaded in arbitrary order, and are processed concurrently with burn chain blocks.  However, Stacks blocks are _accepted_ into the chain state according to a partial ordering induced by the blockchain's parent/child relationships:  for Stacks block _B_ to be accepted, its parent _A_ must have first been accepted.  This PR takes advantage of this fact to assign each Stacks block an _arrival index_, which is a total ordering on Stacks blocks that arises from the fact that `StacksChainState` processes blocks sequentially (but subject to the parent/child partial ordering).  The ordering of a set of blocks' arrival indexes reflects the partial ordering: if _B_ is a descendant of _A_, then the arrival index of _B_ is greater than the arrival index of _A_.

For example, consider the following Stacks forks:

```
              D <-- E
             /
A <-- B <-- C <-- F <-- G <-- H
```

One possible assignment of arrival indexes to blocks could be:

| Block | Arrival Index |
| -------- | ----------------- |
| A        | 1                   |
| B        | 2                   |
| C        | 3                   |
| D        | 4                   |
| E        | 5                   |
| F        | 6                   |
| G       | 7                    |
| H        | 8                   |

Each `BlockSnapshot` contains an `arrival_index` column that is initialized to a non-zero integer once the block it elected is marked as accepted (`BlockSnapshot`s that do not elect blocks or whose blocks have not yet been accepted have an `arrival_index` of 0).

The arrival index is leveraged to make it so that the MARF trie for each `BlockSnapshot` commits to the set of Stacks blocks that have been accepted on its ancestors.  This is handled in `BurnDB::process_new_block_arrivals()`.  When a child `BlockSnapshot` is going to be appended to a parent `BlockSnapshot`, this method queries all `BlockSnapshots` whose Stacks blocks have been accepted since the parent's burn block (i.e. those that have higher arrival indexes), and for each such snapshot, identifies it as either an ancestor or not an ancestor.  For those that are ancestors, it adds a MARF key/value pair that maps the Stacks block hash to its block height.  In addition, as it is processing these ancestors, the method identifies the canonical Stacks chain tip in this burn chain fork as the Stacks block hash with the highest height (i.e. these are recorded in each `BlockSnapshot` for each Stacks block that has been accepted).  This pointer is written to the child `BlockSnapshot`.  Then, when the child `BlockSnapshot` is committed, its corresponding MARF trie contains key/value pairs for all Stacks blocks that have been accepted so far on the burn chain fork it represents, and the child `BlockSnapshot` contains a pointer to the highest Stacks fork within it.  This method also adds a MARF key/value pair for the highest `arrival_index` processed on this burn chain fork, so that when the next `BlockSnapshot` is appended to it, it'll skip over `BlockSnapshot`s that have already been processed.

Using our example above, suppose each Stacks block corresponds to a burn chain block as follows (burn chain blocks are identified by lower-case letters):

```
              D <-- E
              g <-- h <-- i <-- j
             /
A <-- B <-- C <-- F <-- G <-- H
a <-- b <-- c <-- d <-- e <-- f
```

The canonical burn chain fork is `a,b,g,h,i,j`, so the canonical Stacks fork is `A,B,D,E` (burn blocks `i` and `j` did not elect any blocks, and burn blocks `c` and `g` share `b` as a parent).  Suppose that between burn block `g` and burn block `h` being processed, Stacks block `C, D, F, G` are processed (i.e. `g`'s highest-seen arrival index is 2, since Stacks block `B` was the last Stacks block processed before `g` was appended).  Then, when burn block `h` is appended, the code identifies snapshots `c,g,d,e` as `BlockSnapshots` with higher arrival indexes, and identifies only `g` as a `BlockSnapshot` that is an ancestor with a higher arrival index.  So, the MARF for `h` will commit to `D` as having arrived.  Since `h`'s parent `g` committed to a lower Stacks block as its highest-known Stacks block (`B`), `h` will instead point to `D`.  Note that `E` hasn't been processed yet -- in fact, `E` _cannot_ be processed until `h` is accepted into the `BurnDB`, since validating `E` requires `h` to be present.

Alone, this change to the `BurnDB`'s MARF trie and `BlockSnapshot`s would make it so that whenever a burn chain block is newly processed, you can use its `BlockSnapshot` to (a) test whether or not a given Stacks block has been accepted onto this burn chain fork, and (b) determine what the highest such Stacks block is (in both cases, excluding the Stacks block that it elected).  However, this does not help you identify the canonical Stacks chain tip when taking into consideration Stacks blocks that have been downloaded and accepted since then -- e.g. given the `BlockSnapshot` for `h`, you can only learn from the MARF that `D` is the highest Stacks block.

To address this, the `BurnDB` has also been updated to track Stacks blocks that have arrived _since_ a particular burn chain block has processed, and which will be considered for inclusion into the MARF once a _child_ of the burn chain block is processed.  This information is reflected in the new `canonical_accepted_stacks_blocks` table, which pairs a burn header hash (`tip_burn_header_hash`) with an accepted Stacks block's burn hash (`burn_header_hash`), block hash (`stacks_block_hash`), and height (`block_height`).

This table, combined with the MARF, combined with a given `BlockSnapshot`'s canonical chain tip pointer, is used to implement the pointer maintenance algorithm in `BurnDB::set_stacks_block_accepted_at_tip`.  When a Stacks block is accepted, one of three things will be true:

* This Stacks block is a child of the canonical chain tip pointed to by the given `BlockSnapshot`.  The course of action is to update the `BlockSnapshot`'s canonical chain tip to point to this new Stacks block instead.  A record for this block is also added to the `canonical_accepted_stacks_blocks` table.

* The Stacks block is a child of one of the Stacks blocks in this `BlockSnapshot`'s burn chain fork.  If so, then it has a height we can query -- either from the MARF, or from the `canonical_accepted_stacks_blocks` tables.  If this height exceeds this `BlockSnapshot`'s canonical burn chain pointer, then the course of action is to update this pointer to point to this new block (in other words, this is the case where a non-canonical Stacks block fork in this burn chain fork overtakes the canonical Stacks fork).  Otherwise, this block is nevertheless on a non-canonical Stacks fork in this burn chain fork, so a record of it should be kept in case one of its children overtakes the canonical Stacks fork in a subsequent call.  Either way, a record for this block is added to the `canonical_accepted_stacks_blocks` table.

* The Stacks block is not a child of any Stacks blocks in this `BlockSnapshot`'s burn chain fork.  No action is taken.

Whichever of these things is true, the course of action taken will ensure that the given `BlockSnapshot` continues to point to the tip of the longest Stacks fork in the burn chain fork it represents.

The algorithm called by `StacksChainState::process_next_staging_block()` calls the helper method `BurnDB::set_stacks_block_accepted`, which simply runs the above algorithm on the canonical burn chain fork.

## How to test

I've been testing this as follows:

1. Set up a bitcoin regtest node:

```bash
$ cat /tmp/regtest.conf 
chain=regtest
disablewallet=0
txindex=1
server=1
rpcuser=helium-node
rpcpassword=secret
rpcport=18332
port=18444
```

2. Spin up a bitcoin regtest node (`rm -rf ~/.bitcoin/regtest/; bitcoind -regtest -conf=/tmp/regtest.conf`)

3. Spin up a Neon master node controller with this config (only change should be the block time):
```bash
$ cat config.toml.default 
[neon]
rpc_bind = "0.0.0.0:28443"
block_time = 10000
miner_address = "mtFzK54XtpktHj7fKonFExEPEGkUMsiXdy"
bitcoind_rpc_host = "127.0.0.1:18443"
bitcoind_rpc_user = "helium-node"
bitcoind_rpc_pass = "secret"
```

4. Set up a local Neon leader
```
$ cat ./conf/local-leader-conf.toml 
[node]
rpc_bind = "127.0.0.1:20443"
p2p_bind = "127.0.0.1:20444"
seed = "0000000000000000000000000000000000000000000000000000000000000000"
local_peer_seed = "0000000000000000000000000000000000000000000000000000000000000000"
miner = true

[burnchain]
chain = "bitcoin"
mode = "neon"
peer_host = "127.0.0.1"
rpc_port = 28443
peer_port = 18444

[[mstx_balance]]
# Private key: b8d99fd45da58038d630d9855d3ca2466e8e0f89d3894c4724f0efc9ff4b51f001
address = "ST2ZRX0K27GW0SP3GJCEMHD95TQGJMKB7G9Y0X1MH"
amount = 10000000000000000
[[mstx_balance]]
# Private key: 3a4e84abb8abe0c1ba37cef4b604e73c82b1fe8d99015cb36b029a65099d373601
address = "ST26FVX16539KKXZKJN098Q08HRX3XBAP541MFS0P"
amount = 10000000000000000
[[mstx_balance]]
# Private key: 052cc5b8f25b1e44a65329244066f76c8057accd5316c889f476d0ea0329632c01
address = "ST3CECAKJ4BH08JYY7W53MC81BYDT4YDA5M7S5F53"
amount = 10000000000000000
[[mstx_balance]]
# Private key: 9aef533e754663a453984b69d36f109be817e9940519cc84979419e2be00864801
address = "ST31HHVBKYCYQQJ5AQ25ZHA6W2A548ZADDQ6S16GP"
amount = 10000000000000000

# [[events_observer]]
# endpoint = "127.0.0.1:8080"
# events_keys = ["*"]
```

5. Start the local Neon leader
```
BLOCKSTACK_DEBUG=1 RUST_BACKTRACE=1 cargo run start --config=./conf/local-leader-conf.toml
```

6. After it catches up with the bitcoin node, kill the bitcoin node and neon controller.  Note how long the bitcoin chain was.
7. Wait a minute or two for the Neon master node to discover that it can't talk to the bitcoin node anymore.
8. Repeat steps 2 and 3 to re-start the Bitcoin chain
9. Watch the Neon leader reprocess the bitcoin chain, and once the bitcoin chain gets longer than the chain was in step 6, you'll see it start mining a new Stacks chain.  An example output is as follows (note the two chains):

```bash
$ sqlite3 /tmp/"$(ls -Ut --color=never /tmp | grep stacks-testnet | head -n 1)"/chainstate/chain-00000080-testnet/blocks/staging.db 'select height,burn_header_hash,anchored_block_hash,parent_burn_header_hash,parent_anchored_block_hash from staging_blocks;'
1|061fb6a53139326373235d1ae9c243b84441d1b5cdee234d5a3762d63abcd5a7|64b1c26deebd1be6c722e84377bf02942252f4e0c2f76d883e71f0f2bf4b6936|0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000
2|62eef2475fb94c2a97422cb9593c3129649d702af33c66f5eeefd7c7ba679283|06d9dfd0ec94f46a5284460ecaa37086e48f1ecc6fabfd19f50d0ccaa97be6db|061fb6a53139326373235d1ae9c243b84441d1b5cdee234d5a3762d63abcd5a7|64b1c26deebd1be6c722e84377bf02942252f4e0c2f76d883e71f0f2bf4b6936
3|2129f40051129fc1773f17bf4122aaba540c9aa49ffe738a48fa218ceb323ff0|955123b83df6093b3a341384d5a8c8430611c611fa409e3130e31574f17c4e42|62eef2475fb94c2a97422cb9593c3129649d702af33c66f5eeefd7c7ba679283|06d9dfd0ec94f46a5284460ecaa37086e48f1ecc6fabfd19f50d0ccaa97be6db
4|7e1cba1c0277a6ec2d3cf1dc297efede0d27366e53fb44bd57ff5fd74c89e0b3|1328720019aa20a5aeaa1f4e54bec8ac978696caf80b66d29531043c9005296e|2129f40051129fc1773f17bf4122aaba540c9aa49ffe738a48fa218ceb323ff0|955123b83df6093b3a341384d5a8c8430611c611fa409e3130e31574f17c4e42
1|34104145d072f49beacd529a5885a807420b40e240e73b0e3c6a936b85ead014|fc98a2495330735d900c8b55eb6b8a6c5ce6e37c09b3dcb5c1de59c351e6d31e|0000000000000000000000000000000000000000000000000000000000000000|0000000000000000000000000000000000000000000000000000000000000000
2|3dcecb07431ab3fb5444e1b33b04b16ce215933752fa97fccf99cb2f7b40495e|ce45c0a6d455acec4f8c4e0f8706c0181d001f6630ac4993e5b91940e7b48b5c|34104145d072f49beacd529a5885a807420b40e240e73b0e3c6a936b85ead014|fc98a2495330735d900c8b55eb6b8a6c5ce6e37c09b3dcb5c1de59c351e6d31e
3|3bb723a7e8d19b6260a73d35302fd78c7ba1c4387ff8afffa38823b7405538d0|134c12a328e72e3374f3ab28ff6cf317cdcac931215092e71ad5d6563914afae|3dcecb07431ab3fb5444e1b33b04b16ce215933752fa97fccf99cb2f7b40495e|ce45c0a6d455acec4f8c4e0f8706c0181d001f6630ac4993e5b91940e7b48b5c
4|61c6d26e014585658ab1c374b217405e291186382f739c1ab55806d94ced0bbd|e26212da80111c0dd3ae74f7f145c07cff6c21267583b7677cd737c67f440e37|3bb723a7e8d19b6260a73d35302fd78c7ba1c4387ff8afffa38823b7405538d0|134c12a328e72e3374f3ab28ff6cf317cdcac931215092e71ad5d6563914afae
```

10. Verify that two burnchain histories got processed in the burn database.  Note the duplicate block heights at 112 and lower, which indicates the presence of a burnchain fork.
```bash
$ sqlite3 /tmp/"$(ls -Ut --color=never /tmp | grep stacks-testnet | head -n 1)"/burnchain/db/bitcoin/regtest/burn.db/data.db 'select block_height,burn_header_hash from snapshots order by block_height desc limit 15'
118|61c6d26e014585658ab1c374b217405e291186382f739c1ab55806d94ced0bbd
117|3bb723a7e8d19b6260a73d35302fd78c7ba1c4387ff8afffa38823b7405538d0
116|3dcecb07431ab3fb5444e1b33b04b16ce215933752fa97fccf99cb2f7b40495e
115|34104145d072f49beacd529a5885a807420b40e240e73b0e3c6a936b85ead014
114|196bac3b3b9fcc67d58da88505ecad5641594a5aa10b22e1ae5800f6d602aa1d
113|385eacc4ef98385eb34162836ac4ab1e76c1c6bafa793eea1f667560bae7582b
112|7e1cba1c0277a6ec2d3cf1dc297efede0d27366e53fb44bd57ff5fd74c89e0b3
112|6119ff538bcc6ff397c8cbb7f14929f240ac143acc13db9cae1669158c74c0fc
111|2129f40051129fc1773f17bf4122aaba540c9aa49ffe738a48fa218ceb323ff0
111|137287d647000c978e598299c0e39b3ea63392a5ee9bfb42f90d478e738ef7a5
110|62eef2475fb94c2a97422cb9593c3129649d702af33c66f5eeefd7c7ba679283
110|32a286526b25a27299c7357422f1eded513c79b1efc9ed0bd094507fd7b926e4
109|2d1a45f397d812f8f70a1dca58b782b7a6947ad28a73d6538fef445dcb4477a1
109|061fb6a53139326373235d1ae9c243b84441d1b5cdee234d5a3762d63abcd5a7
108|44de866f01ded930446c59595db9773f6dbc8eaea3873dd1ab0874e62f24c6ef
```

### CODE REVIEW

File: testnet/src/node.rs [hunk 1]
```diff
@@ -185,7 +186,8 @@ impl Node {
         node.spawn_peer_server();
 
         loop {
-            if let Ok(Some(ref chain_tip)) = node.chain_state.get_stacks_chain_tip() {
+            let burndb = BurnDB::open(&burndb_path, true).expect("BUG: failed to open burn database");
```
Comment (lgalabru) [inline testnet/src/node.rs:189]: Why do we need `readwrite`?

File: src/chainstate/stacks/db/blocks.rs [hunk 2]
```diff
@@ -3080,25 +3098,15 @@ impl StacksChainState {
...
-                Ok(Some(rows.pop().unwrap()))
-            },
-            _ => {
-                // should be impossible since this is the primary key
-                panic!("Got two or more block rows with same burn and block hashes");
-            }
-        }
+    pub fn get_stacks_chain_tip(&self, burndb: &BurnDB) -> Result<Option<StagingBlock>, Error> {
+        let (burn_bhh, block_bhh) = BurnDB::get_canonical_stacks_chain_tip_hash(burndb.conn())?;
+        let sql = "SELECT * FROM staging_blocks WHERE processed = 1 AND orphaned = 0 AND burn_header_hash = ?1 AND anchored_block_hash = ?2";
```
Comment (lgalabru) [inline src/chainstate/stacks/db/blocks.rs:3107]: Definitely a separate issue, but should we think about doing a pass and adding indexes on fields in the different tables / dbs?

File: src/chainstate/burn/db/burndb.rs [hunk 3]
```diff
@@ -281,11 +326,20 @@ const BURNDB_SETUP : &'static [&'static str]= &[
 
         num_sortitions INTEGER NOT NULL,
 
+        stacks_block_accepted INTEGER NOT NULL,        -- set to 1 if we fetched and processed this Stacks block
+        stacks_block_height INTEGER NOT NULL,           -- set to the height of the stacks block, once it's processed
+        arrival_index INTEGER NOT NULL,                 -- (global) order in which this Stacks block was processed
+
+        canonical_stacks_tip_height INTEGER NOT NULL,   -- height of highest known Stacks fork in this burn chain fork
+        canonical_stacks_tip_hash TEXT NOT NULL,        -- hash of highest known Stacks fork's tip block in this burn chain fork
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply src/chainstate/burn/db/burndb.rs:334]: Per [1], Sqlite won't enforce the `VARCHAR(32)` type.  We've been using `TEXT` everywhere else in the codebase for this reason, and enforcing types using trait implementations of `FromRow` and `FromColumn`.

[1] https://www.sqlite.org/faq.html

File: src/chainstate/burn/db/burndb.rs [hunk 4]
```diff
@@ -604,16 +679,252 @@ impl BurnDB {
...
+        tx.execute("INSERT OR REPLACE INTO canonical_accepted_stacks_blocks (tip_burn_block_hash, burn_block_hash, stacks_block_hash, block_height) VALUES (?1, ?2, ?3, ?4)", args)
+            .map_err(db_error::SqliteError)?;
+        Ok(())
+    }
+
+    /// Get an accepted stacks block header in a fork whose chain tip has not yet committed
+    /// to it.
+    fn get_accepted_stacks_block_pointer(conn: &Connection, tip_burn_header_hash: &BurnchainHeaderHash, stacks_block_hash: &BlockHeaderHash) -> Result<Option<AcceptedStacksBlockHeader>, db_error> {
+        let args : &[&dyn ToSql] = &[tip_burn_header_hash, stacks_block_hash];
+        query_row(conn, "SELECT * FROM canonical_accepted_stacks_blocks WHERE tip_burn_block_hash = ?1 AND stacks_block_hash = ?2", args)
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply src/chainstate/burn/db/burndb.rs:743]: Although you can't enforce it in Sqlite, this query is guaranteed to never return more than one row.  This is because Stacks block entries don't ever get added to `canonical_accepted_stacks_blocks` unless they are first processed by `StacksChainState::process_next_staging_block()`.  By construction, each Stacks block in a given burn chain fork (identified by `tip_burn_header_hash`) will have a unique hash within that fork.  But sure, I can add this check.

[the remark this answers is not in the document]
Comment (kantai) [reply src/chainstate/burn/db/burndb.rs:743]: Note that  `util::db::query_expect_row` implements a version that panics if more than one row is returned.

File: src/main.rs [hunk 5]
```diff
@@ -56,13 +59,11 @@ fn main() {
...
         }
 
-        use burnchains::bitcoin::spv;
-
         let height = argv[2].parse::<u64>().expect("Invalid block height");
         let headers_path = &argv[3];
 
-        let header_opt = spv::SpvClient::read_block_header(headers_path, height).unwrap();
-        match header_opt {
+        let spv_client = spv::SpvClient::new(headers_path, 0, Some(height), BitcoinNetworkType::Mainnet, false, false).expect("FATAL: could not instantiate SPV client");
```
[the remark this answers is not in the document]
Comment (jcnelson) [reply src/main.rs:65]: Will just make it a CLI argument.

File: testnet/src/node.rs (hunk 1 above)
Comment (jcnelson) [reply testnet/src/node.rs:189]: We don't.  Will fix.

File: src/chainstate/stacks/db/blocks.rs (hunk 2 above)
Comment (jcnelson) [reply src/chainstate/stacks/db/blocks.rs:3107]: I can add an index over `processed` and `orphaned`.

File: src/main.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (jcnelson) [reply src/main.rs]: Fixed in 2b749d6

File: src/chainstate/stacks/db/blocks.rs (hunk 2 above)
Comment (jcnelson) [reply src/chainstate/stacks/db/blocks.rs:3109]: Fixed in 90c7c96

File: src/chainstate/burn/db/burndb.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (jcnelson) [reply src/chainstate/burn/db/burndb.rs]: Fixed in 90c7c96

File: testnet/src/node.rs (hunk 1 above)
Comment (jcnelson) [reply testnet/src/node.rs]: Fixed in 046aee8

**Comment by diwakergupta** [comment]
I was trying out this PR on my follower:
- started a follower with default neon config
- few minutes later, the neon miner happened to restart
- follower detected the re-org, started walking back the burnchain until block 321, then started to download blocks again
- before it finished downloading all blocks, follower crashed (around block 211)

Stack trace:

```
INFO [1588248688.100] [src/burnchains/burnchain.rs:912] Downloading burnchain block 208 out of 321...
thread '<unnamed>' panicked at 'FATAL: failed to store leader key to Sqlite: SqliteError(SqliteFailure(Error { code: ConstraintV
iolation, extended_code: 2067 }, Some("UNIQUE constraint failed: leader_keys.public_key")))', src/libcore/result.rs:1165:5
stack backtrace:
INFO [1588248688.213] [src/burnchains/burnchain.rs:912] Downloading burnchain block 209 out of 321...
INFO [1588248688.303] [src/burnchains/burnchain.rs:912] Downloading burnchain block 210 out of 321...
INFO [1588248688.420] [src/burnchains/burnchain.rs:912] Downloading burnchain block 211 out of 321...
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::expect
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
  16: blockstack_lib::chainstate::burn::db::burndb::BurnDB::store_burnchain_transaction                                [34/4243]
             at src/chainstate/burn/db/burndb.rs:951
  17: blockstack_lib::chainstate::burn::db::burndb::BurnDB::append_chain_tip_snapshot
             at src/chainstate/burn/db/burndb.rs:1111
  18: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_checked_block_ops
             at src/burnchains/burnchain.rs:647
  19: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block_ops
             at src/burnchains/burnchain.rs:678
  20: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block_txs
             at src/burnchains/burnchain.rs:741
  21: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block
             at src/burnchains/burnchain.rs:753
  22: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::sync_with_indexer::{{closure}}
             at src/burnchains/burnchain.rs:899
```

The `main` thread also crashed, stack trace:
```
INFO [1588248688.709] [src/burnchains/burnchain.rs:914] Failed to feed burnchain block header 211: "SendError(..)"
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any', src/libcore/result.rs:1165:5                         stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88          1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt                                                                                                    at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205                                                                                          10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139                                                                                         14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::unwrap
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:933                                            16: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::sync_with_indexer
             at src/burnchains/burnchain.rs:930
  17: stacks_node::burnchains::bitcoin_regtest_controller::BitcoinRegtestController::receive_blocks                                             at testnet/src/burnchains/bitcoin_regtest_controller.rs:137                                                             18: <stacks_node::burnchains::bitcoin_regtest_controller::BitcoinRegtestController as stacks_node::burnchains::BurnchainControlle
r>::sync
             at testnet/src/burnchains/bitcoin_regtest_controller.rs:553
  19: stacks_node::run_loop::neon::RunLoop::start
             at testnet/src/run_loop/neon.rs:78
  20: stacks_node::main
             at testnet/src/main.rs:77
  21: std::rt::lang_start::{{closure}}
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  22: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:48
  23: std::panicking::try::do_call
             at src/libstd/panicking.rs:287
  24: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  25: std::panicking::try
             at src/libstd/panicking.rs:265
  26: std::panic::catch_unwind
             at src/libstd/panic.rs:396
  27: std::rt::lang_start_internal
             at src/libstd/rt.rs:47
  28: std::rt::lang_start
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libstd/rt.rs:61
  29: stacks_node::print_version
```

**Comment by diwakergupta** [comment]
Not sure if it's isolated to this PR and a prior issue, but also hit this on a clean restart of the follower (no working dir set):

```
INFO [1588250996.391] [src/net/relay.rs:752] Processing newly received blocks: 6                                          [64/7047]
thread '<unnamed>' panicked at 'FATAL: failed to append snapshot: SqliteError(SqliteFailure(Error { code: DatabaseBusy, extended_co
de: 5 }, Some("database is locked")))', src/libcore/result.rs:1165:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:188
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:205
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:464
  11: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:373
  12: rust_begin_unwind
             at src/libstd/panicking.rs:302
  13: core::panicking::panic_fmt
             at src/libcore/panicking.rs:139
  14: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  15: core::result::Result<T,E>::expect
             at /rustc/73528e339aae0f17a15ffa49a8ac608f50c6cf14/src/libcore/result.rs:960
  16: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_checked_block_ops
             at src/burnchains/burnchain.rs:647
  17: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block_ops
             at src/burnchains/burnchain.rs:678
  18: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block_txs
             at src/burnchains/burnchain.rs:741
  19: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::process_block
             at src/burnchains/burnchain.rs:753
  20: blockstack_lib::burnchains::burnchain::<impl blockstack_lib::burnchains::Burnchain>::sync_with_indexer::{{closure}}
             at src/burnchains/burnchain.rs:899
```

**Comment by kantai** [comment]
How does this change process Stacks blocks in non-canonical burnchain forks?

For example:

Burnchain:

a -> b -> c
  \_> d

Where `d` has a sortition, and the Stacks block `d'` is received.

Will that Stacks block be accepted or rejected? I _think_ that currently it would be rejected, since before calling `preprocess_anchored_block` (I believe something like `src/net/mod.rs:1947` will reject the block). Is that the intended behavior?

**Comment by jcnelson** [comment]
@diwakergupta the "database is locked" error is distinct from this PR.  I'm working on a different PR that addresses this.

The `UNIQUE constraint failed` error is new.  Will investigate.

**Comment by jcnelson** [comment]
> Will that Stacks block be accepted or rejected? I think that currently it would be rejected, since before calling preprocess_anchored_block (I believe something like src/net/mod.rs:1947 will reject the block). Is that the intended behavior?

Yes.  The node doesn't accept blocks that are not on the canonical burn chain fork.  Any attempt to do so would result in a DoS vector, since it would allow an underpowered burnchain miner to feed the node a cheap, endless stream of low PoW blocks with sortitions.  However, the node won't delete blocks in the event of a burnchain reorg, so if a burnchain fork flip-flops between canonical, non-canonical, and canonical again, the Stacks blocks processed on it will be preserved.

**Comment by jcnelson** [comment]
> The UNIQUE constraint failed error is new. Will investigate.

Figured it out.  The miner is rebooting with the same seed, so it's generating the same sequence of VRF keys when it mines.  The code right now has a SQL constraint that all VRF keys are unique, across all burnchain forks.  This is a bug -- it's unreasonable to require this because it opens a DoS vector whereby someone can submit the same VRF key to two burnchain forks, and if both become canonical at some point, the node will crash.  The code already enforces the constraint that each VRF key is unique within its burnchain fork (which is what we're after), so the solution is to drop this constraint.  Will fix.

**Comment by kantai** [comment]
> Yes. The node doesn't accept blocks that are not on the canonical burn chain fork. Any attempt to do so would result in a DoS vector, since it would allow an underpowered burnchain miner to feed the node a cheap, endless stream of low PoW blocks with sortitions. However, the node won't delete blocks in the event of a burnchain reorg, so if a burnchain fork flip-flops between canonical, non-canonical, and canonical again, the Stacks blocks processed on it will be preserved.

How would these low PoW blocks even have been accepted into the burndb? Wouldn't processing those in and of itself be a DoS vector?

Secondly, if we aren't accepting blocks for non-canonical burnchain blocks, can't the checks for "stacks blocks accepted since parent burn block was accepted" be simplified? i.e., either _all_ such stacks blocks are children of the parent's canonical stacks tip, or _none_ of them are?

**Comment by jcnelson** [comment]
> How would these low PoW blocks even have been accepted into the burndb? Wouldn't processing those in and of itself be a DoS vector?

Sorry, I think I miscommunicated.  Of course we wouldn't process such low PoW blocks, for the reason you pointed out.  I was saying that, hypothetically, even if we did, we wouldn't want to process the associated Stacks blocks.

> Secondly, if we aren't accepting blocks for non-canonical burnchain blocks, can't the checks for "stacks blocks accepted since parent burn block was accepted" be simplified? i.e., either all such stacks blocks are children of the parent's canonical stacks tip, or none of them are?

Not really.  Suppose there are two long-lived burnchain forks that flip-flop between being the canonical fork.  We'd want to make sure that the Stacks fork we accept as the canonical fork corresponds to the longest Stacks fork on the canonical burnchain, since the long-lived nature of the burnchain forks will all but guarantee that these two sets of Stacks forks will have diverged.

I agree that this is unlikely to happen in Bitcoin mainnet.  However, this can easily happen on Bitcoin testnet, and moreover, it can easily happen to a chain that an app chain is using as its burnchain.  So, we'll need to address the problem of tracking which burnchain fork has which Stacks blocks sooner or later (and I'd rather address it sooner, so we have more time to test it).

**Comment by jcnelson** [comment]
@diwakergupta addressed the `UNIQUE constraint failed` issue in 8d2f6af

**Comment by kantai** [comment]
> Not really. Suppose there are two long-lived burnchain forks that flip-flop between being the canonical fork. We'd want to make sure that the Stacks fork we accept as the canonical fork corresponds to the longest Stacks fork on the canonical burnchain, since the long-lived nature of the burnchain forks will all but guarantee that these two sets of Stacks forks will have diverged.

I see -- in the event that a burnchain block which wasn't on the canonical fork then is on the canonical burnchain fork, in that interim period, Stacks blocks that belong both to this fork and the previously canonical burnchain fork may have been "newly" processed, and need to rescanned, so there would be a subset of the processed blocks that is valid on the new burnchain fork.

**Comment by jcnelson** [comment]
> I see -- in the event that a burnchain block which wasn't on the canonical fork then is on the canonical burnchain fork, in that interim period, Stacks blocks that belong both to this fork and the previously canonical burnchain fork may have been "newly" processed, and need to rescanned, so there would be a subset of the processed blocks that is valid on the new burnchain fork.

Yup.  Determining which blocks need to be added to the now-canonical chain tip is handled using the arrival index.  Each time we do such a scan for a tip (i.e. when appending a new tip to it), we make its MARF index commit to the highest arrival index processed (so that a subsequent scan only considers blocks processed since then).

File: src/chainstate/burn/db/burndb.rs [hunk 6]
```diff
@@ -604,16 +681,268 @@ impl BurnDB {
...
+                Some(accepted_header) => Some(accepted_header.height),
+                None => match BurnDB::index_value_get(tx, &burn_tip.burn_header_hash, &parent_key)? {
+                    // this block builds on a block accepted _before_ this burn chain tip was processed?
+                    Some(height_str) => Some(height_str.parse::<u64>().expect(&format!("BUG: MARF stacks block key '{}' does not map to a u64", parent_key))),
+                    None => None
+                }
+            };
+            match height_opt {
+                Some(height) => {
+                    if stacks_block_height > height && stacks_block_height > burn_tip.canonical_stacks_tip_height {
```
Comment (kantai) [inline src/chainstate/burn/db/burndb.rs:801]: If `stacks_block_height <= height`, that should be some sort of corruption error, right?

File: src/chainstate/burn/db/burndb.rs [hunk 7]
```diff
@@ -604,16 +681,268 @@ impl BurnDB {
...
+        let old_max_arrival_index = old_max_arrival_index_str.parse::<u64>().expect("BUG: max arrival index is not a u64");
+        let max_arrival_index = BurnDB::get_arrival_index(tx)?;
+
+        let mut new_block_arrivals = vec![];
+
+        // find all Stacks block hashes who arrived since this parent_tip was built.
+        for ari in old_max_arrival_index..(max_arrival_index+1) {
+            let arrival_sn = match BurnDB::get_snapshot_by_arrival_index(tx, ari)? {
+                Some(sn) => sn,
+                None => {
```
Comment (kantai) [inline src/chainstate/burn/db/burndb.rs:894]: What would cause this to return `None`?

File: src/chainstate/burn/db/burndb.rs (hunk 6 above)
Comment (jcnelson) [reply src/chainstate/burn/db/burndb.rs:801]: Yes, I believe so.  If this were true, then we would have processed a Stacks block out-of-order on this burnchain fork (which should have been prevented by a correct implementation of `StacksChainState::process_next_staging_block`).  Will change to a runtime assert and see if it makes a difference.

File: src/chainstate/burn/db/burndb.rs (hunk 7 above)
Comment (jcnelson) [reply src/chainstate/burn/db/burndb.rs:894]: This can happen only when the database is being initialized -- i.e. before the first `BlockSnapshot` gets inserted.

File: src/burnchains/burnchain.rs [hunk 8]
```diff
@@ -915,34 +896,55 @@ impl Burnchain {
...
+            Ok(last_processed)
         });
 
         // feed the pipeline!
+        let input_headers = indexer.read_headers(start_block + 1, end_block + 1)?;
+        let mut downloader_result : Result<(), burnchain_error> = Ok(());
         for i in 0..input_headers.len() {
-            downloader_send.send(Some(input_headers[i].clone()))
-                .map_err(|_e| burnchain_error::ThreadChannelError)?;
+            info!("Downloading burnchain block {} out of {}...", start_block + 1 + (i as u64), end_block);
```
Comment (kantai) [inline src/burnchains/burnchain.rs:912]: Should this be a debug rather than an `info!`? This makes followers very chatty.

**Comment by jcnelson** [comment]
> This PR looks good to me -- however, it seems like these changes are exacerbating SQLite locking issues, and I don't think we can merge this until those are resolved (running a follower on my machine works for only a few minutes before DB busy error causes the node to stop processing blocks).

I agree.  I'll send my other PR (built on top of this PR) that deals with sqlite locking.

File: src/burnchains/burnchain.rs (hunk 8 above)
Comment (jcnelson) [reply src/burnchains/burnchain.rs:912]: What I really want here is some kind of progress indication that tells the user how long it'll be until they have all the blocks and can start querying the chainstate and sending transactions.  This really should be done by some kind of RPC endpoint (maybe /v2/info) that tells you how many burnchain blocks are still downloading and how many Stacks blocks (i.e. sortitions) are still downloading.  This is just meant to be a poor man's stand-in for that.

Comment (jcnelson) [reply src/burnchains/burnchain.rs:912]: Happy to switch back to `debug!`

Comment (jcnelson) [reply src/burnchains/burnchain.rs]: fixed in e1583e1

File: src/chainstate/burn/db/burndb.rs (hunk 6 above)
Comment (jcnelson) [reply src/chainstate/burn/db/burndb.rs]: Fixed in 2881929

**Comment by jcnelson** [comment]
Superseded by #1522
