### PR TITLE
Fix/2407

### LINKED ISSUE #2407: Performance: don't ask for another peer's inventory if we already have all the blocks for it
If the peer has all of the blocks for a given reward cycle, then it has no need to ask any other peer for its inventory as long as its PoX bitvector agrees with that peer.  The only time the local node needs to ask a peer for a block inventory vector is if the local node is (a) missing one or more blocks or microblocks in that reward cycle, and (b) does _not_ have the anchor block for that reward cycle.

### PR DESCRIPTION
**Pull request by jcnelson**
Fixes #2407.  The node will only scan the last N reward cycles of a remote peer's inventory, but every so often (e.g. 12 hours), it will scan everyone's.

### CODE REVIEW

**Comment by jcnelson** [comment]
Okay, this PR does the following:

* Makes it so the node will only synchronize the last few reward cycles in the inventory state machine (configurable under `[connection_options]` as `inv_reward_cycles`, default is 6).  Every 12 hours, it will do a full inventory synchronization (configurable under `[connection_options]` as `full_inv_sync_interval`).
* Makes it so the block downloader will always begin scanning for blocks to download at the block sortition height that the inventory scan last started at.  This means that most of the time, the downloader will by default only scan the last 6 reward cycles (but it will scan all of them on a full inv sync).
* Makes it so the block antientropy protocol will only consider at most `inv_sync_interval` reward cycles at once, but also make it cycle through all reward cycles (just through multiple p2p state machine passes).  In doing so, I discovered and fixed a couple of bugs that was preventing the antientropy protocol from pushing data to nodes that were more than one reward cycle out-of-sync, and was preventing it from sending the same block more than once (even if there were other nodes that needed it).  I added an antientropy stress test as a Neon integration test.

**Comment by jcnelson** [comment]
Still not ready quite yet -- the Neon node run loop isn't correctly inferring whether or not we're in the initial block download when in the first reward cycle.  This, in turn, is causing the anti-entropy protocol to just blast out blocks and microblocks to all its neighbors as they arrive (which is what we want when it's _not_ in IBD mode, but is completely inappropriate while in IBD mode due to its frequency).

File: src/net/p2p.rs [hunk 1]
```diff
@@ -3010,6 +3063,29 @@ impl PeerNetwork {
...
+                            // height we just synchronized
+                            let start_download_sortition =
+                                if let Some(ref inv_state) = self.inv_state {
+                                    debug!(
+                                    "{:?}: Begin downloader synchronization at sortition height {}",
+                                    &self.local_peer, inv_state.block_sortition_start
+                                );
+                                    inv_state.block_sortition_start
+                                } else {
+                                    // really unreachable, but why tempt fate?
```
Comment (lgalabru) [inline src/net/p2p.rs:3077]: Should we emit an error log in this case?

File: src/chainstate/burn/db/sortdb.rs [hunk 2]
```diff
@@ -1970,6 +1970,10 @@ impl PoxId {
         }
         (ret, count)
     }
+
+    pub fn num_inventory_reward_cycles(&self) -> usize {
+        self.0.len() - 1
```
Comment (pavitthrap) [inline src/chainstate/burn/db/sortdb.rs:1975]: Use `checked_sub` here maybe?

File: src/net/download.rs [hunk 3]
```diff
@@ -2347,7 +2358,12 @@ impl PeerNetwork {
             self.init_block_downloader();
         }
 
-        let last_inv_update_at = self.inv_state.as_ref().unwrap().last_change_at;
+        let mut last_inv_update_at = 0;
```
Comment (pavitthrap) [inline src/net/download.rs:2361]: style nit: could do `(last_inv_update_at, inv_start_sortition) = match self.inv_state { Some(x) => ...`

Comment (jcnelson) [reply src/net/download.rs:2361]: Done

File: src/net/p2p.rs (hunk 1 above)
Comment (jcnelson) [reply src/net/p2p.rs:3100]: Done

**Comment by jcnelson** [comment]
> Still not ready quite yet -- the Neon node run loop isn't correctly inferring whether or not we're in the initial block download when in the first reward cycle (it thinks we're not). This, in turn, is causing the anti-entropy protocol to just blast out blocks and microblocks to all its neighbors as they arrive (which is what we want when it's not in IBD mode, but is completely inappropriate while in IBD mode due to its frequency).

Okay, I think both of these are fixed.  I leave a mainnet and testnet follower running for a few days and confirm, but so far it looks good.

File: src/net/p2p.rs [hunk 4]
```diff
@@ -2789,22 +2828,34 @@ impl PeerNetwork {
                                         block_stats,
                                     )?
                                 {
+                                    let index_block_hash = StacksBlockHeader::make_index_block_hash(
+                                        &parent_consensus_hash,
+                                        &parent_block_hash
+                                    );
+
+                                    if parent_consensus_hash == highest_snapshot.consensus_hash {
+                                        // This parent block was just sortition'ed
```
Comment (kantai) [inline src/net/p2p.rs:2837]: What happens if the antientropy protocol pushes blocks that have just been chosen?

Comment (jcnelson) [reply src/net/p2p.rs:2837]: It shouldn't, and I've confirmed this when running the node on mainnet.  This condition should make it so the anti-entropy protocol only pushes blocks and microblocks after at least one subsequent sortition has happened (since the block or confirmed microblock stream to be pushed must have a different consensus hash than the burnchain's canonical tip).

Comment (kantai) [reply src/net/p2p.rs:2837]: Right -- my question is, why not? What's the downside of pushing the just-chosen block?

Comment (jcnelson) [reply src/net/p2p.rs:2837]: It's a DDoS vector.  If we did this, then all nodes you're connected to will all push the block to you at about the same time.  We avoid this today by making it so that all your connected neighbors will only push you a (much smaller) `BlocksAvailable` message when they have obtained a block.  This, in turn, causes you to go and ask the neighbors for the block data if you do not yet have it already.

Comment (jcnelson) [reply src/net/p2p.rs:2837]: Hilariously, I've witnessed this DDoS-y behavior already.  Remember the network outage from a few weeks ago when we lost a couple blocks for a few hours?  Turns out, a new nodes will have obtained, but not processed, these blocks because the invalid microblock stream that they confirm has been lost forever.  So new nodes don't know that old nodes already have this block, and have simply orphaned it because it confirmed a too-big stream.  As such, a new node will periodically send the invalid block to old nodes that did process the (now-lost) microblock stream over and over because the old nodes report it missing while the new nodes report it as present but unprocessed.

This behavior doesn't pose a systemic risk simply because new nodes booting from this branch will need a new chainstate anyway, so they'll all obtain this unprocessable block and will all believe that their peers already have it.

Comment (kantai) [reply src/net/p2p.rs:2837]: Ah, okay, that makes sense

**Review by kantai — APPROVED** [review]

**Review by lgalabru — APPROVED** [review]
LGTM, Thank you @jcnelson !
