### PR TITLE
Fix: #2053, apply should not add functions to stack while evaling args

### LINKED ISSUE #2053: Circular reference error on nested function invocation
**Describe the bug**

In Clarity, nested calls to custom function fails with an unexpected _circular reference_ error.

**Steps To Reproduce**

Evaluate in the [Clarity REPL](https://lgalabru.github.io/clarity-repl/):

```clojure
(define-read-only (identity (n int)) n)
(begin (identity (identity 1)))
```
=>
`Runtime Error: Unchecked(CircularReference(["S1G2081040G2081040G2081040G208105NK8PE5.snippet-0:identity"]))`

**Expected behavior**

Should evaluate to the original value.

**Environment (please complete the following information):**

[Clarity REPL](https://lgalabru.github.io/clarity-repl/):

**Additional context**

Possibly due to inconsistent invocation of custom functions.

### PR DESCRIPTION
**Pull request by kantai**
## Description

Fixes #2053, by waiting until after eval'ing function arguments to put an applied function on the stack. To prevent excessive apply/eval recursion, the call stack needs to track apply-depth in addition to stack depth.

## Type of Change
- Bug fix

## Does this introduce a breaking change?
Yes, this is a consensus breaking change.

## Testing information

This includes a test that witnesses the original issue #2053, which now passes. The apply-depth change is covered by the existing tests:

```
    vm::tests::contracts::test_arg_stack_depth
    vm::tests::contracts::test_cc_stack_depth
    vm::tests::contracts::test_cc_trait_stack_depth
```

### CODE REVIEW

File: src/vm/tests/simple_apply_eval.rs [hunk 1]
```diff
@@ -911,6 +911,18 @@ fn test_lets() {
...
+fn test_2053_stacked_user_funcs() {
+    let test = "
+(define-read-only (identity (n int)) n)
+(begin (identity (identity 1)))
+";
+
+    let expectation = Value::Int(1);
+
+    assert_eq!(expectation, execute(test));
+}
```
Comment (jcnelson) [inline src/vm/tests/simple_apply_eval.rs:924]: With the changes to how we measure stack depth, the VM would rightfully prevent us from doing something like `(begin (identity (identity (identity (identity ( ... (identity 1))))))) ... )`, right?

Comment (kantai) [reply src/vm/tests/simple_apply_eval.rs:924]: Yep -- it prevented this before this PR, but the way this was enforced was what was causing this problem. The tests:

```
    vm::tests::contracts::test_arg_stack_depth
    vm::tests::contracts::test_cc_stack_depth
```

demonstrate that prevention.

Comment (kantai) [reply src/vm/tests/simple_apply_eval.rs:924]: In order to preserve that behavior, we needed to add the `apply_depth` value.

**Review by jcnelson — APPROVED** [review]
LGTM!

**Review by lgalabru — APPROVED** [review]
Looks good to me, thank you @kantai!
