### PR TITLE
Fix #1591: as-max-len should update runtime type annotation

### LINKED ISSUE #1591: as-max-len? fails with a list that is too long
**Describe the bug**
When calling `as-max-len?` with a list with a size value longer than the indicated length the transaction fails with an execution error:

Contract snippet: 
```
(define-data-var token-ids (list 10 uint) (list))
...
(as-max-len? (append (var-get token-ids) next-id) u10)
```

Error:
Transaction execution error: 
Unchecked(TypeValueError(ListType(ListTypeData { max_len: 10, entry_type: UIntType }), List(ListData { data: [UInt(1)], type_signature: ListTypeData { max_len: 11, entry_type: UIntType } })))' 

**Steps To Reproduce**
add the above snippet to a contract and call the function containing the snippet

**Expected behavior**
should return `none`

**Environment (please complete the following information):**
 - clarity 1.13
- stack-blockchain 3aa7f7925303499b01033274b83c736a65d20e64

**Additional context**
This happens in unit tests using clarity 1.13 as well as mocknet 

Error on mocknet:
```
 Invalid contract-call transaction f3ffd85bf250f80b9f45aed7021f15bb0fecbee79af97fa5cf041ae8554cdbd7: 
Interpreter(Unchecked(TypeValueError(ListType(ListTypeData { max_len: 10, entry_type: UIntType }), 
List(ListData { data: [UInt(1)], type_signature: ListTypeData { max_len: 11, entry_type: UIntType } }))))
```

### PR DESCRIPTION
**Pull request by kantai**
`as-max-len` needs to update the returned iterable's runtime type.

### CODE REVIEW

File: src/vm/types/signatures.rs [hunk 1]
```diff
@@ -215,6 +215,14 @@ impl ListTypeData {
         (*self.entry_type, self.max_len)
     }
 
+    // if checks like as-max-len pass, they may _reduce_
+    //   but should not increase the type signatures max length
+    pub fn reduce_max_len(&mut self, new_max_len: u32) {
+        if new_max_len <= self.max_len {
+            self.max_len = new_max_len;
+        }
```
Comment (jcnelson) [inline src/vm/types/signatures.rs:223]: Can it ever be the case that the code calls `reduce_max_len()` with a `new_max_len` that is larger than `self.max_len`?

File: src/vm/tests/contracts.rs [hunk 2]
```diff
@@ -683,6 +683,19 @@ fn test_at_unknown_block() {
     with_marfed_environment(test, true);
 }
 
+#[test]
+fn test_as_max_len() {
+    fn test(owned_env: &mut OwnedEnvironment) {
+        let contract = "(define-data-var token-ids (list 10 uint) (list))
+                        (var-set token-ids 
+                           (unwrap! (as-max-len? (append (var-get token-ids) u1) u10) (err 10)))";
```
Comment (jcnelson) [inline src/vm/tests/contracts.rs:691]: Is there a way this function can test that `token-ids` now has length `u10`?

Also, it's not clear from the language documentation what should happen if the `M` value (`u10`) is less than `N` (the list's length) -- it returns `(none)` right?  There's no way to truncate a list?

Comment (friedger) [reply src/vm/tests/contracts.rs:691]: There's no way to truncate a list? My plan was to copy the elements to a shorter list.

File: src/vm/types/signatures.rs (hunk 1 above)
Comment (kantai) [reply src/vm/types/signatures.rs:223]: Yep— if a list already had a small type annotation when passed to as-max-Len, new_max_len would be greater than the original. In that case, the list type annotation should remain as is.

File: src/vm/tests/contracts.rs (hunk 2 above)
Comment (kantai) [reply src/vm/tests/contracts.rs:691]: > Is there a way this function can test that token-ids now has length u10?

Yep— that’s what the assignment to data variable checks. 

> Also, it's not clear from the language documentation what should happen if the M value (u10) is less than N (the list's length) -- it returns (none) right?

Yes, it returns none. I can improve the description in the docs generation.

Comment (kantai) [reply src/vm/tests/contracts.rs:691]: And no, there’s no truncate or slice function at the moment. Would certainly be open to adding a native function for this, but it could be implemented with the fold function for now.

Comment (jcnelson) [reply src/vm/tests/contracts.rs:691]: @friedger want to open an issue to suggest adding a truncate-list built-in function?

File: src/vm/docs/mod.rs [hunk 3]
```diff
@@ -407,8 +407,11 @@ const ASSERTS_MAX_LEN_API: SpecialAPI = SpecialAPI {
     signature: "(as-max-len? buffer u10)",
     description: "The `as-max-len?` function takes a length N (must be a literal) and a buffer or list argument, which must be typed as a list
 or buffer of length M and outputs that same list or buffer, but typed with max length N.
-At runtime, a check is performed, which if it fails, returns a (none) option.",
-    example: "(as-max-len? (list 2 2 2) u3) ;; Returns (some (list 2 2 2))"
+
+This function returns an optional type with the resulting iterable. If the inputt iterable is less than
```
Comment (lgalabru) [inline src/vm/docs/mod.rs:411]: typo on `inputt`
