### PR TITLE
Fix: Detecting dependencies in tuple constructors

### LINKED ISSUE #1625: Tuple cares about function ordering in physical file
**Describe the bug**
When a `tuple` is used, `checkContract()` will fail if the tuple requires a private function that is declared below the `tuple` usage

**Steps To Reproduce**
A broken and working example can be found at https://github.com/xmakina/clarity-tuple-function-order/tree/master/contracts and below

**Expected behavior**
Tuple should be able to access a private function from anywhere in the physical script file

**Environment (please complete the following information):**
 - OS: Windows 10
 - Rust version: N/A
 - Version of the appropriate binary / software package: "@blockstack/clarity": "^0.1.16"

**Additional context**

__working.clar__
```
(define-private (get-zero)
    0
)

(define-read-only (get-score)
    (ok 
        (tuple
            (score (get-zero))
        )
    )
)
```
__broken.clar__
```
(define-read-only (get-score)
    (ok 
        (tuple
            (score (get-zero))
        )
    )
)

(define-private (get-zero)
    0
)
```

### PR DESCRIPTION
**Pull request by kantai**
This resolves #1625 by fixing a bug in `vm::ast::definition_sorter` --- tuple constructors weren't parsed correctly when probing for dependencies (they need to look for lists of pairs, but the previous code was looking for lists of lists of pairs).

### CODE REVIEW

File: src/vm/analysis/type_checker/tests/mod.rs [hunk 1]
```diff
@@ -859,6 +859,29 @@ fn test_high_order_map() {
...
+(define-private (get-zero)
+    0
+)
+
+1
+";
+
+    assert_eq!(&mem_type_check(snippet).unwrap().0.unwrap().to_string(),
+               "int");
+}
```
Comment (jcnelson) [inline src/vm/analysis/type_checker/tests/mod.rs:883]: Would it be possible to add a test that included the exact example code that triggered this bug?

Comment (kantai) [reply src/vm/analysis/type_checker/tests/mod.rs:883]: I think this test is the exact sample code from the issue -- this is `broken.clar`.

**Comment by kantai** [comment]
Thanks for the reviews! I'll work on fixing the build failure (it looks like a bad version of async-std is getting pulled in), and then merge.
